app/home/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField
from wtforms.ext.sqlalchemy.fields import QuerySelectField
from app.models import Eventos

class SearchEvent(FlaskForm):
    eventos=QuerySelectField(query_factory=lambda: Eventos.query.all(), get_label="evento_name")
    submit=SubmitField('Buscar')

app/home/routes.py
from app import app, db
from flask import (render_template, request, redirect, url_for, session,
                   flash, Blueprint, abort, json
                   )

from flask_login import current_user, login_required

from app.models import Inversionistas, Organizaciones, Products, Kart, Eventos
from app.admin.forms import Variations
from app.home.forms import SearchEvent

home = Blueprint('home', __name__)


@home.route('/admin/dashboard', methods=['GET'])
@login_required
def admin_dashboard():
    # preventing non admins from accessing the page
    if not current_user.is_admin:
        abort(403)
    return render_template('admin/admin_dashboard.html', title="Dashboard")


@home.route('/', methods=['GET'])
def landing():
    return redirect(url_for("home.homepage"))


@home.route('/home', methods=['GET'])
def homepage():
    products = Products.query.all()
    products = [product for product in products if product.promotion_value > 0]

    if current_user.is_anonymous:
        count = 0
    else:
        count = Kart.query.filter_by(user_id=current_user.id).count()

    return render_template("home/index.html", title='Website name',
                           products=products, count=count, size=len(products))


@home.route('/productos')
def canasta():
    if current_user.is_anonymous:
        count = 0
    else:
        count = Kart.query.filter_by(user_id=current_user.id).count()

    page = request.args.get('page', 1, type=int)

    products = Products.query\
        .order_by(Products.product_name).paginate(page=page, per_page=6)

    return render_template("home/canasta.html", title="Canasta Agricola", products=products, count=count)


@home.route('/organizaciones')
def organizaciones():

    if current_user.is_anonymous:
        count = 0
    else:
        count = Kart.query.filter_by(user_id=current_user.id).count()

    page = request.args.get('page', 1, type=int)

    organizaciones = Organizaciones.query\
        .order_by(Organizaciones.organizacion_name).paginate(page=page, per_page=6)

    return render_template("home/organizaciones.html", title="Organizaciones", organizaciones=organizaciones, count=count)


@home.route('/organizaciones/<int:id>', methods=["GET", "POST"])
def organizacion_details(id):

    if current_user.is_anonymous:
        count = 0
    else:
        count = Kart.query.filter_by(user_id=current_user.id).count()

    organizacion = Organizaciones.query.filter_by(id=id).first_or_404()
    products = Products.query.filter_by(organizacion_id=id).all()

    return render_template("home/organizacion_details.html",
                           organizacion=organizacion, title=organizacion.organizacion_name, products=products, count=count)


@home.route('/productos/<int:id>', methods=["GET", "POST"])
def product_details(id):
    if current_user.is_anonymous:
        count = 0
    else:
        count = Kart.query.filter_by(user_id=current_user.id).count()
        user = current_user.id

    form = Variations()

    product_detail = Products.query.filter_by(id=id).first_or_404()
    organizacion = Organizaciones.query.filter_by(id=product_detail.organizacion_id).first_or_404()

    form.amount.choices = [i+1 for i in range(product_detail.product_stock)]

    # add to cart
    if form.validate_on_submit():
        # annonymous users
        if current_user.is_anonymous:
            flash(
                'Por favor, haz login para poder agregar items a tu carrito de compras.', 'warning')
            return redirect(url_for("home.product_details", id=product_detail.id))
        # authenticated users
        subtotal = (int(form.amount.data)) * (product_detail.product_price - (product_detail.product_price * (product_detail.promotion_value/100)))
        cart = Kart(user_id=user, product_id=product_detail.id,
                    quantity=form.amount.data, subtotal=subtotal)
        db.session.add(cart)
        db.session.commit()

        flash(f"{product_detail.product_name} has been added to cart")
        return redirect(url_for('home.product_details', id=product_detail.id))
    return render_template("home/productdetails.html",
                           product_detail=product_detail, title=product_detail.product_name,
                           form=form, count=count, organizacion=organizacion)


@home.route('/inversionistas')
def inversionistas():

    if current_user.is_anonymous:
        count = 0
    else:
        count = Kart.query.filter_by(user_id=current_user.id).count()


    page = request.args.get('page', 1, type=int)

    inversionistas = Inversionistas.query\
        .order_by(Inversionistas.inversionista_name).paginate(page=page, per_page=6)

    return render_template("home/inversionistas.html", title="Inversionistas", inversionistas=inversionistas, count=count)


@home.route('/inversionistas/<int:inversionista_id>', methods=["GET", "POST"])
def inversionista_details(inversionista_id):

    if current_user.is_anonymous:
        count = 0
    else:
        count = Kart.query.filter_by(user_id=current_user.id).count()

    inversionista = Inversionistas.query.filter_by(
        id=inversionista_id).first_or_404()

    return render_template("home/inversionista_details.html",
                           inversionista=inversionista, title=inversionista.inversionista_name, count=count)


@home.route('/eventos', methods=["GET", "POST"])
def eventos():

    if current_user.is_anonymous:
        count = 0
    else:
        count = Kart.query.filter_by(user_id=current_user.id).count()

    long = -76.60631917174642
    lat = 2.4419131406694277
    zoom = 12.5
    eventos = Eventos.query.all()
    form = SearchEvent()
    if form.validate_on_submit():
        long = form.eventos.data.evento_long
        lat = form.eventos.data.evento_lat
        zoom = 15
    return render_template("home/eventos.html", title="Eventos", form=form, eventos=eventos, long=long, lat=lat, zoom=zoom, count=count)

app/templates/home/canasta.html
{% extends "base.html" %}
{% block title %}{{ title }}{% endblock title %}

{% block body %}

<div class="row d-block">
  {% for product_list in products.items %}
  <a href="{{ url_for('home.product_details', id=product_list.id) }}">
  <div class="col l4 s12 m6">
    <div class="card-panel hoverable" style="max-height:360px; background-color:#FFFFFF;">
      <div class="card-image" style="margin-left:auto;margin-right: auto;">
        <div class="thumbnail" style="height:220px;margin-bottom: 0px;">
          <img class="responsive-img" src="{{ product_list.product_image }}" style="height:100%;">
        </div>
        <h6 class="title">
          <span class="product-name">{{ product_list.product_name }}</span>
        </h6>
        <div class="price-container clearfix">
          <span class="price-box" style="margin-bottom:0px;white-space:normal;">
          <span class="price">
            <span>$</span>
            <span>{{ product_list.product_price }}</span>
          </span>
          </span>
        </div>
      </div>
    </div>
  </div>
  </a>
  {% endfor %}
</div>

{% for page_num in products.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
{% if page_num %}
    {% if products.page == page_num %}
        <a class="btn btn-info mb-4" href="{{ url_for('home.canasta', title=title, page=page_num)}}">{{page_num}}</a>
    {% else %}
    <a class="btn btn-outline-info mb-4" href="{{ url_for('home.canasta', title=title, page=page_num)}}">{{page_num}}</a>
    {%endif%}
{%endif%}
{% endfor %}
</div>
{% endblock %}

app/templates/home/eventos.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}{{ title }}{% endblock title%}
{% block body %}

<div class="container mt-1 mb-3 justify-content-center align-items-center">

  <div class="row">
    <div class="col">
      <form class="form d-flex justify-content-center align-items-center" method="post" role="form">
        {{ form.csrf_token() }}
        <div class="form-group m-1">
          {{ form.eventos(class="form-control")}}
        </div>
        <input id="submit" class="btn btn-outline-success" name="submit" type="submit" value="Buscar">
      </form>
    </div>
  </div>

  <div class="row">
    <div class="col d-flex justify-content-center align-items-center">
      <div id='map' style='width: 50rem; height: 25rem;'></div>
    </div>
  </div>
  <script>

    mapboxgl.accessToken = 'pk.eyJ1IjoieWVyc29uYXJnb3RlIiwiYSI6ImNrcXRwMW85dTAyMHgycHBmYXhyaDNhcGgifQ.3HG4MTBEq8Ib3_JNWr2lug';
    var map = new mapboxgl.Map({
      container: 'map',
      style: 'mapbox://styles/mapbox/streets-v11',
      center: [{{long}}, {{lat}}],
      zoom: {{zoom}}
    });

    {% for evento in eventos %}

      new mapboxgl.Marker({
      color: "#5FAFFF",
      draggable: false})
      .setLngLat([{{evento.evento_long}}, {{evento.evento_lat}}])
      .setPopup(
            new mapboxgl.Popup({ offset: 25 }) // add popups
            .setHTML("<strong>{{evento.evento_name}}</strong>"))
      .addTo(map);
    {% endfor %}

  </script>
</div>

{% endblock %}

app/templates/home/index.html
{% extends "base.html" %}
{% block title %}Cauca Agro SOS{% endblock title%}
{% block body %}

{% include "promotions/carousel_promotions.html" %}
{% block carousel %}
{% endblock %}

{% include "promotions/promotions.html" %}
{% block promos %}
{% endblock %}

{% endblock %}

app/templates/home/inversionista_details.html
{% extends "base.html" %}
{% block title %}{{ title }}{% endblock title%}
{% block body %}

<div class="container">
  <div class="row">

    <div class="col d-flex justify-content-center align-items-center">
      <img  class="responsive-img" src="{{ inversionista.inversionista_image }}">
    </div>

    <div class="col">
      <div class="row">
        <div class="col d-flex justify-content-center align-items-center">
          <h4>{{ inversionista.inversionista_name }}</h4>
        </div>
      </div>

      <div class="row">
        <div class="col m-1">
          <h5 class="m-1">Descripci&oacute;n</h5>
          <p class="m-1">{{ inversionista.inversionista_desc }}</p>
        </div>
      </div>
      
      <div class="row">
        <div class="col m-1">
          <h5 class="m-1">Email</h5>
          <p class="m-1">{{ inversionista.inversionista_email }}</p>
        </div
      </div>

    </div>
  </div>
</div>

{% endblock %}

app/templates/home/inversionistas.html
{% extends "base.html" %}
{% block title %}{{ title }}{% endblock title %}

{% block body %}

<div class="row d-block">
  {% for inversionista_list in inversionistas.items %}
  <a href="{{ url_for('home.inversionista_details', inversionista_id=inversionista_list.id) }}">
    <div class="col l4 s12 m6">
      <div class="card-panel hoverable" style="max-height:360px; background-color:#FFFFFF;">
        <div class="card-image" style="margin-left:auto;margin-right: auto;">
          <div class="thumbnail" style="height:220px;margin-bottom: 0px;">
            <img class="responsive-img" src="{{ inversionista_list.inversionista_image }}" style="height:100%;">
          </div>
          <h6 class="title">
            <span class="product-name">
              {{ inversionista_list.inversionista_name }}
            </span>
          </h6>
        </div>
      </div>
    </div>
  </a>
  {% endfor %}
</div>
{% for page_num in inversionistas.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
{% if page_num %}
{% if page_num.page == page_num %}
<a class="btn btn-info mb-4" href="{{ url_for('home.inversionistas', title=title, page=page_num)}}">{{page_num}}</a>
{% else %}
<a class="btn btn-outline-info mb-4"
  href="{{ url_for('home.inversionistas', title=title, page=page_num)}}">{{page_num}}</a>
{%endif%}
{%endif%}
{% endfor %}
</div>
{% endblock %}

app/templates/home/organizacion_details.html
{% extends "base.html" %}
{% block title %}{{ title }}{% endblock title%}
{% block body %}

<div class="container">
  <div class="row">

    <div class="col d-flex justify-content-center align-items-center">
      <img  class="responsive-img" src="{{ organizacion.organizacion_image}}">
    </div>

    <div class="col">
      <div class="row">
        <div class="col d-flex justify-content-center align-items-center">
          <h4>{{ organizacion.organizacion_name }}</h4>
        </div>
      </div>

      <div class="row">
        <div class="col m-1">
          <h5 class="m-1">Ubicaci&oacute;n</h5>
          <p class="m-1">{{ organizacion.organizacion_location }}</p>
        </div>
      </div>
      
      <div class="row">
        <div class="col m-1">
          <h5 class="m-1">Tel&eacute;fono</h5>
          <p class="m-1">{{ organizacion.organizacion_phone }}</p>
        </div
      </div>

    </div>
  </div>
</div>

{% include "promotions/promotions.html" %}
{% block promos %}
{% endblock %}

{% endblock %}

app/templates/home/organizaciones.html
{% extends "base.html" %}
{% block title %}{{ title }}{% endblock title %}

{% block body %}

<div class="row d-block">
  {% for organizacion_list in organizaciones.items %}
    <a href="{{ url_for('home.organizacion_details', id=organizacion_list.id) }}">
          <div class="col l4 s12 m6">
        <div class="card-panel hoverable" style="max-height:360px; background-color:#FFFFFF;">    
          <div class="card-image" style="margin-left:auto;margin-right: auto;">
            <div class="thumbnail" style="height:220px;margin-bottom: 0px;">
                <img class="responsive-img" src="{{ organizacion_list.organizacion_image }}" style="height:100%;">
            </div>
            <h6 class="title">
                <span class="product-name">
                    {{ organizacion_list.organizacion_name }}
                </span>
            </h6>
          </div>
        </div>
      </div>
    </a>
  {% endfor %}
</div>

{% for page_num in organizaciones.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
  {% if page_num %}
    {% if page_num.page == page_num %}
      <a class="btn btn-info mb-4" href="{{ url_for('home.organizaciones', title=title, page=page_num)}}">{{page_num}}</a>
    {% else %}
      <a class="btn btn-outline-info mb-4" href="{{ url_for('home.organizaciones', title=title, page=page_num)}}">{{page_num}}</a>
    {%endif%}
  {%endif%}
{% endfor %}

</div>
{% endblock %}

app/templates/home/productdetails.html
{% extends "base.html" %}
{% block title %}{{ title }}{% endblock title%}
{% block body %}
{% if product_detail %}

<div class="container mt-1 mb-3"
  <div class="card" style="width: 50%;">
    <img src="{{ product_detail.product_image }}" class="card-img-top" alt="{{ product_detail.name }}">
    <div class="card-body">
      <h5 class="card-title">{{ product_detail.product_name }}</h5>

       <div class="row m-1 justify-content-center align-items-center">
          <div class="col m">
            <h6 class="card-subtitle mt-0">Organizaci&oacute;n</h6>
          </div>
          <div class="col">
            <a type="button" class="btn btn-outline-info" href="{{ url_for('home.organizacion_details', id=organizacion.id) }} ">
              <p class="card-text mt-0">{{ organizacion.organizacion_name }}</p>
            </a>
          </div>
      </div>

      <div class="row m-1 justify-content-center align-items-center">
          <div class="col">
            <h6 class="card-subtitle mt-0">Stock</h6>
          </div>
          <div class="col">
            <p class="card-text mt-0">{{ product_detail.product_stock }}</p>
          </div>
      </div>

       <div class="row m-1 justify-content-center align-items-center">
          <div class="col">
            <h6 class="card-subtitle mt-0">Precio</h6>
          </div>
          <div class="col">
            <p class="card-text mt-0">{{ product_detail.product_price }}</p>
          </div>
      </div>

       <div class="row m-1 justify-content-center align-items-center">
          <div class="col">
            <h6 class="card-subtitle mt-0">Promoci&oacute;n</h6>
          </div>
          <div class="col">
            <p class="card-text mt-0">{{ product_detail.promotion_value }} %</p>
          </div>
      </div>

       <div class="row m-1 justify-content-center align-items-center">
          <div class="col-sm">
            <h6 class="card-subtitle mt-0">Descripci&oacute;n</h6>
          </div>
          <div class="col-sm">
            <p class="card-text mt-0">{{ product_detail.product_description }}</p>
          </div>
      </div>

      <form class="form" method="post" role="form">
      {{ form.hidden_tag() }}
       <div class="row justify-content-center align-items-center m-0">
        <div class="col-sm">
        <div class="m-1 form-group">
          <h6>Cantidad</h6>
        </div>
        </div>

        <div class="col-sm">
          <div class="form-group">
            {{ form.amount(class="form-control m-1")}}
          </div>
        </div>
       </div>

       <div class="row">
          <div class="col-sm d-flex justify-content-center align-items-center m-0">
              <div class="form-group"> 
                {{ form.submit(class="btn btn-outline-success") }}
              </div>
          </div>
        </div>
      </form>
  </div>
</div>

{% endif %}
{% endblock %}