app/users/forms.py
from flask_wtf import FlaskForm
from wtforms import(StringField, IntegerField, PasswordField,
                    SubmitField, validators)

from wtforms.validators import ValidationError, DataRequired, Email

from app.models import Users


class CartForm(FlaskForm):
    quantity = IntegerField('1', validators=[DataRequired()])
    submit = SubmitField('Submit')


class ShippingForm(FlaskForm):
    address = StringField('Primary Address', validators=[DataRequired()])
    additional = StringField('Additional Information', validators=[DataRequired()])
    postcode = IntegerField('Postal code', validators=[DataRequired()])
    city = StringField('City', validators=[DataRequired()])
    state = StringField('State', validators=[DataRequired()])
    submit = SubmitField('Submit')


class RequestResetForm(FlaskForm):
    email = StringField('Email Address', validators=[DataRequired(), Email()])
    submit = SubmitField('Request Password Reset')

    def validate_email(self, email):
        user = Users.query.filter_by(email=email.data).first()
        if user is None:
            raise ValidationError(
                "There is no account with that email. You must register first")


class ResetPasswordForm(FlaskForm):
    password = PasswordField('Password', [validators.Length(min=8, max=25, message="Password must be 8 to 25 characters long"), validators.Required()])
    confirm = PasswordField('Repeat Password', [validators.EqualTo('password', message="Passwords must match.")])
    submit = SubmitField('Reset Password')

app/users/routes.py
from flask import (render_template, request, redirect, url_for,
                   flash, Blueprint, jsonify
                   )

from app.models import Products, Purchase, Users, Shipping, Kart, Orders

import gc

from flask_login import (current_user, login_required
                         )
from app.users.forms import (ShippingForm, RequestResetForm, ResetPasswordForm,
                             CartForm)
from app import db, mail
from flask_mail import Message
from random import randint

users = Blueprint('users', __name__)


def ShippingPrice():
    '''
    calculate the price of shipping if items is greater than 5 shipping is 2500
    else 1200
    '''
    shipping_price = 0
    if current_user.is_authenticated:
        items = Kart.query.filter_by(user_id=current_user.id).all()
        acum = 0
        for item in items:
            acum += item.quantity
        shipping_price = (int(acum / 10) + 1) * 2500
    return shipping_price


def subtotals():
    subtotals = 0
    if current_user.is_authenticated:
        products = Kart.query.filter_by(user_id=current_user.id).all()
        for product in products:
            subtotals += product.subtotal
    return subtotals


@users.route('/cart', methods=["GET", "POST"])
def cart():
    if current_user.is_anonymous:
        count = 0
        user = 0
        user_info = None
        cartlist = []
        shipping = None
    else:
        user = current_user.id
        user_info = Users.query.get(user)
        count = Kart.query.filter_by(user_id=user).count()
        cartlist = Kart.query.filter_by(user_id=user).all()
        shipping = Shipping.query.filter_by(user_id=user).first()

    form = CartForm()

    price = ShippingPrice()
    items_subtotals = subtotals()

    # for annoymous users
    if current_user.is_anonymous:
        flash('Por favor haz login o registrate para poder utilizar el carrito de compras.')
        return render_template('users/cart.html', count=count, cartlist=cartlist,
                               title="Cart", form=form, price=price, items_subtotals=items_subtotals, shipping=shipping)

    if shipping is None:
        flash('Por favor rellena la información del evio(shipping).')
        return redirect(url_for('users.profile'))

    return render_template('users/cart.html', count=count, cartlist=cartlist,
                           title="Cart", form=form, price=price, items_subtotals=items_subtotals, shipping=shipping, user=user_info)


@users.route('/cart/update/<int:id>', methods=["POST"])
def quantity_update(id):
    cart_item = Kart.query.get_or_404(id)
    quantity = request.form["quantity"]
    cart_item.quantity = quantity
    item_total = cart_item.product.product_price * int(quantity)
    cart_item.subtotal = item_total
    items_subtotal = subtotals()
    db.session.commit()
    gc.collect()
    return jsonify({"result": "success", "item_total": item_total, "subtotal": items_subtotal})


@users.route('/cart/remove/<int:id>', methods=["GET", "POST"])
def remove_item(id):
    cart_item = Kart.query.get_or_404(id)
    db.session.delete(cart_item)
    db.session.commit()
    gc.collect()
    return redirect(url_for('users.cart'))


def send_success_mail(user):
    msg = Message('Item(s) Purchased', sender='noreply@demo.com',
                  recipients=[user.email])
    msg.body = f'''You have successfully purchased items from our store.
These items will be shipped withing 48hours, Thank you.
If you did not make this request simply ignore this request and no changes will be made.
'''
    mail.send(msg)


@login_required
@users.route('/order/<int:user>/<int:shipping>', methods=["GET", "POST"])
def order(user, shipping):

    karts = Kart.query.filter_by(user_id=user).all()


    for kart in karts:
        product = Products.query.get_or_404(kart.product_id)
        product.product_stock = product.product_stock - kart.quantity
        db.session.commit()

        purchase = Purchase(product_id=kart.product_id, quantity=kart.quantity, subtotal=kart.subtotal, user_id=kart.user_id)
        db.session.add(purchase)
        db.session.commit()

        order = Orders(user_id=user, shipping_id=shipping, purchase_id=purchase.id)
        db.session.add(order)
        db.session.commit()

        db.session.delete(kart)
        db.session.commit()

    return redirect(url_for('users.profile'))


@login_required
@users.route('/success', methods=["GET"])
def success():
    u = current_user.id
    flash('Transaction successful', 'success')
    if request.method == "GET":
        user = current_user.email
        send_success_mail(user)
        ref = randint(1, 10000)
        order = Orders(user_id=u, order_ref=ref)
        db.session.add(order)
        db.session.commit()
        items = Kart.query.filter_by(user_id=u).all()
        for i in items:
            ids = i.product
            order.my_orders.append(ids)
            db.session.delete(i)
        db.session.commit()
        gc.collect()
    return render_template('users/charge.html')


@login_required
@users.route('/failure')
def failed():
    flash('transaction Failed', 'danger')
    return render_template('users/failed.html')


@users.route('/profile', methods=["GET", "POST"])
def profile():
    if current_user.is_anonymous:
        count = 0
        user = 0
        orders = None
        items = None
    else:
        user = current_user.id
        count = Kart.query.filter_by(user_id=user).count()
        orders = Orders.query.filter_by(user_id=user).all()
        items = Kart.query.filter_by(user_id=user).all()

    form = ShippingForm()
    shipping = Shipping.query.filter_by(user_id=user).all()
    if form.validate_on_submit():
        info = Shipping(address=form.address.data, aditional_indications=form.additional.data,
                            postcode=form.postcode.data, city=form.city.data,
                            state=form.state.data, country=request.form['country'], user_id=user)
        db.session.add(info)
        db.session.commit()
        gc.collect()
        flash('Shipping information was submitted successfully', 'success')
        return redirect(url_for('users.profile'))
    return render_template('users/profile.html', title="Account page", form=form,
                           shipping=shipping, count=count, orders=orders, items=items)


def send_reset_email(user):
    token = user.get_reset_token()
    msg = Message('Password Reset Request', sender='noreply@demo.com',
                  recipients=[user.email])
    msg.body = f'''To reset your password, visit the following link:
{ url_for('users.reset_token', token = token, _external =True) }
If you did not make this request simply ignore this request and no changes will be made.
'''
    mail.send(msg)


@users.route('/profile/reset_password', methods=["GET", "POST"])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('home.homepage'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = Users.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset you password', 'info')
        return redirect(url_for('auth.login'))
    return render_template('users/reset_request.html', title='Reset password',
                           form=form)


@users.route('/profile/reset_password/<token>', methods=["GET", "POST"])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('home.homepage'))
    user = Users.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        user.password_hash = user.set_password(form.password.data)
        db.session.commit()
        gc.collect()
        flash('Your password has been successfully updated', 'success')
        return redirect(url_for('auth.login'))
    return render_template('users/change-password.html', title='Reset password',
                           form=form)

app/templates/users/cart.html
{% extends "base.html" %}
{%block title%}Cart{%endblock title%}
{% block body%}
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
<link href="{{ url_for('static', filename='css/cart.css')}}" rel="stylesheet">
<div class="container">

	<div class="container">
		<div class="row">

				<div class="col">
				</div>
			
				<div class="col">
					<strong>Product</strong>
				</div>
				<div class="col">
						<strong>Price</strong>
				</div>
				<div class="col">
						<strong>Promotion</strong>
				</div>

				<div class="col">
						<strong>Quantity</strong>
				</div>

				<div class="col">
						<strong>Subtotal</strong>
				</div>

				<div class="col">
						<strong>Remove</strong>
				</div>

		</div>
		
		{% for items in cartlist %}

		<div class="row">

			<div class="col">
				<img src="{{ items.product.product_image }}" class="item-img img-responsive"/>
			</div>	

			<div class="col">
        <h6 class="nomargin">
            <p>{{ items.product.product_name }}</p>
        </h6>
			</div>

			<div class="col">
        <span class="iso">$</span>
        <span class="iso">{{ items.product.product_price }}</span>
			</div>

			<div class="col">
        <span class="iso">{{ items.product.promotion_value}}</span>
        <span class="iso">%</span>
			</div>

			<div class="col">
						<p>
              <input type="text" name="quantity" class="qty form-control-sm" id="qty{{items.id}}" value="{{items.quantity}}" readonly>
              <span class="times">x</span>
              <span class="iso">$</span>
              <span class="item-price{{items.id}}">{{ items.product.product_price }}</span>
						</p>
			</div>

			<div class="col">
        <p> 
            <span class="iso">$</span>
            <span class="item-total">{{ items.subtotal }}</span>
        </p>
			</div>

			<div class="col">
					<a href="{{ url_for('users.remove_item', id=items.id) }}" class=" btn btn-outline-danger btn-sm">x</a>
			</div>
		</div>
    <!-- end row -->
		<div class="line"></div>
		{% endfor %}

    <div class="container d-flex justify-content-center align-items-center">
      <span class="m-2"><strong>Subtotal</strong>: {{items_subtotals}}</span>
      <span class="m-2"><strong>Shipping</strong>: {{ price }}</span>
      <span class="m-2"><strong>Total</strong>: {{items_subtotals + price}}</span>
		</div>

    <div class="container">
      <a href="{{ url_for('home.homepage') }}" class="btn btn-outline-dark continue-shopping"><i class="fa fa-angle-left"></i>Continue Shopping</a>
      <a href="#" class="btn btn-success checkout-btn float-right" data-toggle="modal" data-target="#exampleModalCenter">Checkout</a>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">Confirmaci&oacute;n de Compra</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">

            {% if user %}
            <div class="container">
             <fieldset>
                <legend>User Details</legend>  
                <ul class="list-group">
                  <li class="list-group-item">{{user.firstname}}</li>
                  <li class="list-group-item">{{user.lastname}}</li>
                  <li class="list-group-item">{{user.email}}</li>
                  <li class="list-group-item">{{user.phonenumber}}</li>
                </ul>
              </fieldset>
            </div>
            {% endif %}

            {% if shipping %}
            <div class="container">
             <fieldset>
                <legend>Shipping Details</legend>  
                <ul class="list-group">
                  <li class="list-group-item">{{shipping.address}}</li>
                  <li class="list-group-item">{{shipping.aditional_indications}}</li>
                  <li class="list-group-item">{{shipping.postcode }}</li>
                  <li class="list-group-item">{{shipping.city}}, {{shipping.state}}</li>
                  <li class="list-group-item">{{shipping.country}} </li>
                </ul>
              </fieldset>
            </div>
            {% endif %}
          
            {% if items_subtotals > 0 %}
            <div class="container d-flex justify-content-center align-items-center">
              <span class="m-2"><strong>Subtotal</strong>: {{items_subtotals}}</span>
              <span class="m-2"><strong>Shipping</strong>: {{ price }}</span>
              <span class="m-2"><strong>Total</strong>: {{items_subtotals + price}}</span>
            </div>
            {% endif %}
          </div>

          {% if user %}
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <a href="{{ url_for('users.order', user=user.id, shipping=shipping.id) }}" class="btn btn-outline-primary">Finalizar Compra</a>
          </div>
          {% endif %}
        </div>
      </div>
    </div>

{% endblock %}

app/templates/users/change-password.html
{% extends "base.html" %}
{% block title %}Change Password{% endblock %}
{% block body %}
<div class="center">
        <div class="content-section">
            <form method="POST" action="">
                {{ form.hidden_tag() }}
                <div class="form-group">
                        {{ form.password.label(class="form-control-label") }}
                        {{ form.password(class="form-control form-control") }}
                    </div>    
                    <div class="form-group">
                        {{ form.confirm.label(class="form-control-label") }}
                        {{ form.confirm(class="form-control form-control") }}
                    </div>
                
                <div class="form-group">
                    {{ form.submit(class="btn btn-outline-info") }}           
                </div>
            </form>
        </div>
      </div>
{% endblock %}

app/templates/users/charge.html
{% extends "base.html" %}
{% block title %}Payment Sucessful{% endblock %}
{% block header %}

<h3>Thanks for Your Purchase!</h3>

{% endblock %}

app/templates/users/failed.html
{%extends 'base.html' %}
{% block title %}Payment Failed{% endblock %}
{% block header %}
<h3>
    Sorry payments was not Successful
</h3>
{% endblock header %}

app/templates/users/profile.html
{% extends "base.html" %}
{% block title %}Profile{% endblock %}

{% block head %}

{% endblock %}
{% block body %}
<h3>
        Welcome to your profile page
</h3>
<nav>
  <div class="nav nav-tabs" id="nav-tab" role="tablist">
    <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true">Profile</a>
    <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false">Orders</a>
    <a class="nav-item nav-link" id="nav-contact-tab" data-toggle="tab" href="#nav-contact" role="tab" aria-controls="nav-contact" aria-selected="false">Shipping</a>
  </div>
</nav>

<div class="tab-content" id="nav-tabContent mb-5">
<div class="tab-pane fade show active " id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
              
                <ul class="list-group mt-4 center">
                        <li class="list-group-item">{{current_user.firstname }}</li>
                        <li class="list-group-item">{{current_user.lastname }}</li>
                        <li class="list-group-item">{{current_user.email}}</li>
                        <li class="list-group-item">{{current_user.phonenumber }}</li>
                </ul>
</div>

<div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
      <div class="container">
        <table class="table table-striped table-bordered">
          <thead>
            <tr>
              <th> Orden n&uacute;mero </th>
              <th> Fecha </th>
              <th> Producto </th>
              <th> Total </th>
              <th> Direcci&oacute;n </th>
            </tr>
          </thead>
          <tbody>
          {% for order in orders %}
          <tr>
              <td>{{ order.id }}</td>
              <td>{{ order.timestamp.strftime('%d-%m-%Y,  %H:%M:%S')}}</td>
              <td>{{ order.purchase.product.product_name }}</td>
              <td>{{ order.purchase.subtotal }}</td>
              <td>{{ order.shipping.address }}</td>
          </tr>
          {% endfor %}
          </tbody>
      </table>
  </div>
</div>

<!-- shipping-->
<div class="tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab">

        {% if shipping == [] %}

<div  class="container">
        <div class="center">
                
        <form class="form" method="POST">
                {{ form.hidden_tag() }}
                <div class="form-group  required">
                  <label class="control-label" for="Primary Address">{{ form.address.label }}</label>
                  {{ form.address(class="form-control") }}                
                </div>
                <div class="form-group  required">
                  <label class="control-label" for="Secondary Address">{{ form.additional.label }}</label>
                  {{ form.additional(class="form-control") }}
                </div>
                <div class="form-group  required">
                  <label class="control-label" for="Postal Code">{{ form.postcode.label }}</label>
                  {{ form.postcode(class="form-control") }}
                </div>

                <div class="form-group  required">
                  <label class="control-label" for="City">{{ form.city.label }}</label>
                  {{ form.city(class="form-control") }}
                </div>

                <div class="form-group  required">
                  <label class="control-label" for="State">{{ form.state.label }}</label>
                  {{ form.state(class="form-control") }}
                </div>

                <div class="form-group  required">
                        <label class="control-label" for="Country">Country</label>
                        <select class="selectpicker countrypicker form-control"
                                data-live-search="true"
                                data-default="Colombia"
                                data-flag="true" name="country"> 
                        </select>            
                </div>
                {{ form.submit(class="btn btn-primary")}}      
        </form>
        </div>
</div>
         {% else %}
        <fieldset>
                <legend>Shipping Details</legend>  
                <ul class="list-group">
                {% for info in shipping %}
                  <li class="list-group-item">{{info.address}}</li>
                  <li class="list-group-item">{{info.aditional_indications}}</li>
                  <li class="list-group-item">{{info.postcode }}</li>
                  <li class="list-group-item">{{info.city}}, {{info.state}}</li>
                  <li class="list-group-item">{{info.country}} </li>
                {% endfor %}
                </ul>
        </fieldset>
                {% endif %}
</div>
</div>

{% endblock %}

app/templates/users/reset_request.html
{% extends "base.html" %}
{% block title %}Reset Request{% endblock %}
{% block body %}
<div class="center">
        <div class="content-section">
            <form method="POST" action="">
                {{ form.hidden_tag() }}
                <div class="form-group">
                        {{ form.email.label(class="form-control-label") }}
                        {{ form.email(class="form-control form-control") }}
                    </div>    
                
                <div class="form-group">
                    {{ form.submit(class="btn btn-outline-info") }}           
                </div>
            </form>
        </div>
      </div>

{% endblock %}