app/admin/routes.py
import os
from flask import (flash, render_template, Blueprint, url_for, abort, redirect,
                   request
                   )
from flask_login import current_user, login_required
from app.admin.forms import OrganizacionForm, ProductForm, InversionistaForm, EventoForm
from app.models import Inversionistas, Organizaciones, Products, Orders, Eventos
from app import photos
from config import Config
import gc, unidecode
from app import db

admin = Blueprint('admin', __name__)


def check_admin():
    if not current_user.is_admin:
        abort(403)


@admin.route('/organizaciones', methods=['GET', 'POST'])
@login_required
def list_organizaciones():
    '''
    Get all product organizacion
    first check if user is an admin
    '''

    check_admin()

    organizaciones = Organizaciones.query.all()

    return render_template('admin/organizaciones/organizaciones.html', title="Organizaciones", organizaciones=organizaciones)


@admin.route('/organizacion/add', methods=['GET', 'POST'])
def add_organizacion():
    """
    add a organizacion to the
    database
    """
    check_admin()

    add_organizacion = True

    form = OrganizacionForm()

    if form.validate_on_submit():
        name = Organizaciones.query.filter(Organizaciones.organizacion_name==form.name.data).first()
        if name:
            flash("Organizacion already exists.")
            return render_template('admin/organizaciones/organizacion.html', action="Add", form=form,
                           add_organizacion=add_organizacion, title="Add Organizacion")

        filename = request.files['image']
        _, f_ext = os.path.splitext(filename.filename)

        name = unidecode.unidecode(form.name.data).replace(' ', '')
        picture_fn = f'{name}{f_ext}'

        photos.save(filename, name=picture_fn)
        url = photos.url(picture_fn)
        organizacion = Organizaciones(
            organizacion_name=form.name.data, organizacion_image=url, organizacion_location=form.location.data, organizacion_phone=form.phone.data)
        try:
            db.session.add(organizacion)
            db.session.commit()
            flash("You have successfully added a new Organizacion")
            gc.collect()
        except Exception:
            flash('Error: Organizacion name already exits. ')

        return redirect(url_for('admin.list_organizaciones'))
    return render_template('admin/organizaciones/organizacion.html', action="Add", form=form,
                           add_organizacion=add_organizacion, title="Add Organizacion")


@admin.route('/organizacion/edit/<int:id>', methods=["GET", "POST"])
def edit_organizacion(id):
    '''
            Edit a organizacion name
    '''

    check_admin()

    add_organizacion = False

    organizacion = Organizaciones.query.get_or_404(id)

    form = OrganizacionForm(obj=organizacion)
    if form.validate_on_submit():
        filename = request.files['image']
        _, f_ext = os.path.splitext(filename.filename)

        name = unidecode.unidecode(form.name.data).replace(' ', '')
        picture_fn = f'{name}{f_ext}'

        # remove the changed picture from the folder
        img_dir = Config.UPLOADED_PHOTOS_DEST+'/'
        old_name = unidecode.unidecode(organizacion.organizacion_name).replace(' ', '')
        _, old_ext = os.path.splitext(organizacion.organizacion_image)
        old_picture_fn = f'{old_name}{old_ext}'

        if os.path.exists(img_dir+old_picture_fn):
            os.remove(img_dir+old_picture_fn)

        photos.save(filename, name=picture_fn)
        url = photos.url(picture_fn)

        organizacion.organizacion_name = form.name.data
        organizacion.organizacion_image = url
        organizacion.organizacion_phone = form.phone.data
        organizacion.organizacion_location = form.location.data

        db.session.commit()
        gc.collect()
        flash("You have successfully edited the organizacion")
        # redirect to the organizacion page
        return redirect(url_for('admin.list_organizaciones'))
    form.name.data = organizacion.organizacion_name
    form.location.data = organizacion.organizacion_location
    form.phone.data = organizacion.organizacion_phone

    return render_template('admin/organizaciones/organizacion.html', action="Edit",
                           add_organizacion=add_organizacion, form=form,
                           organizacion=organizacion, title="Edit Organizacion")


@admin.route('/organizaciones/delete/<int:id>', methods=["GET", "POST"])
def delete_organizacion(id):
    organizacion = Organizaciones.query.get_or_404(id)

    # get image extension
    _, f_ext = os.path.splitext(organizacion.organizacion_image)

    name = unidecode.unidecode(organizacion.organizacion_name).replace(' ', '')
    picture_fn = f'{name}{f_ext}'
    img_dir = Config.UPLOADED_PHOTOS_DEST+'/'

    if os.path.exists(img_dir+picture_fn):
        os.remove(img_dir+picture_fn)

    db.session.delete(organizacion)
    db.session.commit()
    gc.collect()
    flash("You have successfully deleted a Organizacion")

    return redirect(url_for('admin.list_organizaciones'))


'''
	return render_template('admin/organizacion/organizacion.html',
	title = "Delete Organizacion")
'''


@admin.route('/products', methods=['GET'])
@login_required
def list_products():
    check_admin()
    '''
	list all products
	'''
    products = Products.query.all()

    return render_template('admin/products/products.html', title='Products', products=products)


@admin.route('/products/add', methods=["GET", "POST"])
@login_required
def add_product():
    '''
    add a product to the database
    '''

    check_admin()

    add_product = True

    form = ProductForm()
    if form.validate_on_submit():
        filename = request.files['image']
        _, f_ext = os.path.splitext(filename.filename)
        name = unidecode.unidecode(form.name.data).replace(' ', '')
        id_org = form.organizaciones.data.id
        picture_fn = f'{name}{id_org}{f_ext}'
        photos.save(filename, name=picture_fn)
        url = photos.url(picture_fn)

        if form.promotion_value.data is None:
            form.promotion_value.data = 0

        product = Products(product_name=form.name.data, product_price=form.price.data, product_image=url,
                           product_description=form.description.data, product_stock=form.stock.data,
                           promotion_value=form.promotion_value.data, organizacion_id=form.organizaciones.data.id,)
        try:
            # add a product to the database
            db.session.add(product)
            db.session.commit()
            gc.collect()
            flash("You have successfully added a product")
        except:
            # in case product name already exists
            flash("Error in the database")

        # redirect to the roles page
        return redirect(url_for('admin.list_products'))
    # load product template
    return render_template('admin/products/product.html', add_product=add_product,
                           form=form, title="Add Product")


@admin.route('/products/edit/<int:id>',  methods=["GET", "POST"])
@login_required
def edit_product(id):
    '''
    edit product
    '''
    check_admin()

    add_product = False

    product = Products.query.get_or_404(id)
    form = ProductForm(obj=product)
    if form.validate_on_submit():
        filename = request.files['image']
        _, f_ext = os.path.splitext(filename.filename)

        name = unidecode.unidecode(form.name.data).replace(' ', '')
        id_org = form.organizaciones.data.id
        picture_fn = f'{name}{id_org}{f_ext}'

        # remove the changed picture from the folder
        img_dir = Config.UPLOADED_PHOTOS_DEST+'/'
        old_name = unidecode.unidecode(product.product_name).replace(' ', '')
        _, old_ext = os.path.splitext(product.product_image)
        old_picture_fn = f'{old_name}{product.organizacion_id}{old_ext}'

        if os.path.exists(img_dir+old_picture_fn):
            os.remove(img_dir+old_picture_fn)

        photos.save(filename, name=picture_fn)
        url = photos.url(picture_fn)

        product.organizacion_id = form.organizaciones.data.id 
        product.product_name = form.name.data
        product.product_price = form.price.data
        product.product_image = url
        product.product_description = form.description.data
        product.product_stock = form.stock.data
        product.promotion_value = form.promotion_value.data
        db.session.commit()
        gc.collect()

        flash('You have successfully edited a product')
        # redirect to the products page
        return redirect(url_for('admin.list_products'))

    form.name.data = product.product_name
    form.price.data = product.product_price
    form.description.data = product.product_description
    form.stock.data = product.product_stock
    form.promotion_value.data = product.promotion_value

    return render_template('admin/products/product.html', add_product=add_product,
                           form=form, title="Edit Product")


@admin.route('/products/delete/<int:id>', methods=["GET", "POST"])
@login_required
def delete_product(id):
    '''
    Delete a product from the database
    '''
    check_admin()

    product = Products.query.get_or_404(id)

    name = unidecode.unidecode(product.product_name).replace(' ', '')
    id_org = product.organizacion_id
    _, old_ext = os.path.splitext(product.product_image)
    previous_img_name = f'{name}{id_org}{old_ext}'

    img_dir = Config.UPLOADED_PHOTOS_DEST+'/'

    # remove the changed picture from the folder
    if os.path.exists(img_dir+previous_img_name):
        os.remove(img_dir+previous_img_name)

    db.session.delete(product)
    db.session.commit()
    gc.collect()
    flash("You have successfully deleted a product")

    return redirect(url_for('admin.list_products'))


@admin.route('/orders')
@login_required
def list_orders():
    check_admin()
    '''
	list all orders
	'''

app/home/routes.py
from app import app, db
from flask import (render_template, request, redirect, url_for, session,
                   flash, Blueprint, abort, json
                   )

from flask_login import current_user, login_required

from app.models import Inversionistas, Organizaciones, Products, Kart, Eventos
from app.admin.forms import Variations
from app.home.forms import SearchEvent

home = Blueprint('home', __name__)


@home.route('/admin/dashboard', methods=['GET'])
@login_required
def admin_dashboard():
    # preventing non admins from accessing the page
    if not current_user.is_admin:
        abort(403)
    return render_template('admin/admin_dashboard.html', title="Dashboard")


@home.route('/', methods=['GET'])
def landing():
    return redirect(url_for("home.homepage"))


@home.route('/home', methods=['GET'])
def homepage():
    products = Products.query.all()
    products = [product for product in products if product.promotion_value > 0]

    if current_user.is_anonymous:
        count = 0
    else:
        count = Kart.query.filter_by(user_id=current_user.id).count()

    return render_template("home/index.html", title='Website name',
                           products=products, count=count, size=len(products))


@home.route('/productos')
def canasta():
    if current_user.is_anonymous:
        count = 0
    else:
        count = Kart.query.filter_by(user_id=current_user.id).count()

    page = request.args.get('page', 1, type=int)

    products = Products.query\
        .order_by(Products.product_name).paginate(page=page, per_page=6)

    return render_template("home/canasta.html", title="Canasta Agricola", products=products, count=count)


@home.route('/organizaciones')
def organizaciones():

    if current_user.is_anonymous:
        count = 0
    else:
        count = Kart.query.filter_by(user_id=current_user.id).count()

    page = request.args.get('page', 1, type=int)

    organizaciones = Organizaciones.query\
        .order_by(Organizaciones.organizacion_name).paginate(page=page, per_page=6)

    return render_template("home/organizaciones.html", title="Organizaciones", organizaciones=organizaciones, count=count)


@home.route('/organizaciones/<int:id>', methods=["GET", "POST"])
def organizacion_details(id):

    if current_user.is_anonymous:
        count = 0
    else:
        count = Kart.query.filter_by(user_id=current_user.id).count()

    organizacion = Organizaciones.query.filter_by(id=id).first_or_404()
    products = Products.query.filter_by(organizacion_id=id).all()

    return render_template("home/organizacion_details.html",
                           organizacion=organizacion, title=organizacion.organizacion_name, products=products, count=count)


@home.route('/productos/<int:id>', methods=["GET", "POST"])
def product_details(id):
    if current_user.is_anonymous:
        count = 0
    else:
        count = Kart.query.filter_by(user_id=current_user.id).count()
        user = current_user.id

    form = Variations()

    product_detail = Products.query.filter_by(id=id).first_or_404()
    organizacion = Organizaciones.query.filter_by(id=product_detail.organizacion_id).first_or_404()

    form.amount.choices = [i+1 for i in range(product_detail.product_stock)]

    # add to cart
    if form.validate_on_submit():
        # annonymous users
        if current_user.is_anonymous:
            flash(
                'Por favor, haz login para poder agregar items a tu carrito de compras.', 'warning')
            return redirect(url_for("home.product_details", id=product_detail.id))
        # authenticated users
        subtotal = (int(form.amount.data)) * (product_detail.product_price - (product_detail.product_price * (product_detail.promotion_value/100)))
        cart = Kart(user_id=user, product_id=product_detail.id,
                    quantity=form.amount.data, subtotal=subtotal)
        db.session.add(cart)
        db.session.commit()

        flash(f"{product_detail.product_name} has been added to cart")
        return redirect(url_for('home.product_details', id=product_detail.id))
    return render_template("home/productdetails.html",
                           product_detail=product_detail, title=product_detail.product_name,
                           form=form, count=count, organizacion=organizacion)


@home.route('/inversionistas')
def inversionistas():

    if current_user.is_anonymous:
        count = 0
    else:
        count = Kart.query.filter_by(user_id=current_user.id).count()


    page = request.args.get('page', 1, type=int)

    inversionistas = Inversionistas.query\
        .order_by(Inversionistas.inversionista_name).paginate(page=page, per_page=6)

    return render_template("home/inversionistas.html", title="Inversionistas", inversionistas=inversionistas, count=count)


@home.route('/inversionistas/<int:inversionista_id>', methods=["GET", "POST"])
def inversionista_details(inversionista_id):

    if current_user.is_anonymous:
        count = 0
    else:
        count = Kart.query.filter_by(user_id=current_user.id).count()

    inversionista = Inversionistas.query.filter_by(
        id=inversionista_id).first_or_404()

    return render_template("home/inversionista_details.html",
                           inversionista=inversionista, title=inversionista.inversionista_name, count=count)


@home.route('/eventos', methods=["GET", "POST"])
def eventos():

    if current_user.is_anonymous:
        count = 0
    else:
        count = Kart.query.filter_by(user_id=current_user.id).count()

    long = -76.60631917174642
    lat = 2.4419131406694277
    zoom = 12.5
    eventos = Eventos.query.all()
    form = SearchEvent()
    if form.validate_on_submit():
        long = form.eventos.data.evento_long
        lat = form.eventos.data.evento_lat
        zoom = 15
    return render_template("home/eventos.html", title="Eventos", form=form, eventos=eventos, long=long, lat=lat, zoom=zoom, count=count)

app/templates/base.html
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
      <title>
        {%block title%}
        {%endblock title%}
      </title>
      <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}"rel="stylesheet">
      <link href="{{ url_for('static', filename='css/st.css') }}"rel="stylesheet">

      <script src='https://api.mapbox.com/mapbox-gl-js/v2.3.1/mapbox-gl.js'></script>
      <link href='https://api.mapbox.com/mapbox-gl-js/v2.3.1/mapbox-gl.css' rel='stylesheet' />

      {%block head%}
      {%endblock head%}
  </head>

  <body>

  {% include "navbar.html" %}
  {% block navbar %}
  {% endblock %}

  {% include "categories/categories.html" %}
  {% block organizacion%}
  {% endblock %}
 
  {% with messages = get_flashed_messages() %}
  {% if messages %}
  {% for message in messages %}

  <div class="alert alert-info alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  {% endfor %}
  {% endif %}
  {% endwith %}

  <div class="container">
    <script src="{{ url_for('static', filename='js/jquery-3.3.1.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/countrypicker.js') }}"></script>
    {% block body %}
    {% endblock %}
  </div>

  <hr class="footer-break"></hr>

{% include "footer.html" %}
{% block footer %}
{% endblock %}
 
</body>
</html>

app/templates/footer.html
{% block footer %}

<div class="container my-5">
  <footer
          class="text-center text-lg-start text-black"
          style="background-color: #ffffff"
          >
    <!-- Grid container -->
    <div class="container p-4 pb-0">
      <!-- Section: Links -->
      <section class="">
        <!--Grid row-->
        <div class="row">
          <!-- Grid column -->
          <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3">
            <h6 class="text mb-4 font-weight-bold">
              #CaucaAgroSOSTENIBLE
            </h6>
            <p>
              Es una iniciativa
              académica que pretender visibilizar a las familias, emprendimientos, asociaciones y demás, que se dediquen
              a los cultivos productivos y a la transformación de los mismos.
            </p>
          </div>

          <!-- Grid column -->
          <hr class="w-100 clearfix d-md-none" />

          <!-- Grid column -->
          <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mt-3">
            <h6 class="text-uppercase mb-4 font-weight-bold">Siguenos</h6>

            <a href="https://www.facebook.com/">
              <img src="{{ url_for('static',filename='iconmonstr-facebook.svg') }}" class="img-responsive svg-footer">
            </a>

            <a href="https://www.instagram.com/">
              <img src="{{ url_for('static',filename='iconmonstr-instagram.svg') }}" class="img-responsive svg-footer">
            </a>

            <a href="https://twitter.com/?lang=en">
              <img src="{{ url_for('static',filename='iconmonstr-twitter.svg') }}" class="img-responsive svg-footer">
            </a>
          </div>
          <!-- Grid column -->

          <hr class="w-100 clearfix d-md-none" />

          <!-- Grid column -->
          <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mt-3">
            <h6 class="text-uppercase mb-4 font-weight-bold">Informaci&oacute;n</h6>
            <a type="button" class="btn btn-ligth" href="{{ url_for('users.profile') }}">Perfil</a>
          </div>
        </div>
        <!--Grid row-->
      </section>
      <!-- Section: Links -->
    </div>
    <!-- Grid container -->

    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
      © 2021 Copyright
    </div>
    <!-- Copyright -->
  </footer>
  <!-- Footer -->
</div>
<!-- End of .container -->

{% endblock %}

app/templates/head.html
{% extends "base.html" %}
{% block title %}Cauca Agro SOS{% endblock title%}
{% block body %}
  <!-- banner -->
<div class="banner">
  <div class="xf">
    <div class="bd-example" >
    <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
      <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
      <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
      </ol>
    <div class="carousel-inner">
    <div class="carousel-item active" style="min-height:480px;">
      <img src="{{url_for('static', filename='Oferta.png')}}" class="d-block carousel-img-height" alt="...">
    <div class="carousel-caption d-none d-md-block">
      <p>
        <a href="{{url_for('home.homepage')}}"> 
        Ofertas Especiales</a> 
      </p>
    </div>
  </div>
                                            
{% for i in products %}    
{% if i.id in sorter %}
  <div class="carousel-item" style="min-height:480px;">
    <a href="{{url_for('home.product_details',product_name = i.product_name)}}">
    <img src="{{i.product_image}}" class="d-block  carousel-img-height" alt="...">
    <div class="carousel-caption d-none d-md-block">
      <h5>Featured Products</h5>
      <p>{{i.product_name}}</p>
    </div>
    </a>
  </div>
{%endif%}
{%endfor %}
                                            
    <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>

    <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>
</div>  
</div>  

{% endblock %}

app/templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% block body %}
    <div class="content-section">
      
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control") }}
                        <small id="passwordHelpInline" class="text-muted">
                                Must be 8-25 characters long.
                        </small>
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-2">
                    <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                </small>
                <small class="text-muted ml-5">
                    Need An Account? <a class="ml-2" href="{{ url_for('auth.register') }}">Sign Up Now</a>
                </small>
            </div>
        </form>
      </div>

{% endblock%}

app/templates/navbar.html
{% block navbar %}

<div class="container mt-1 mb-3">

  <nav class="navbar navbar-expand-lg navbar-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <h1 class="brand_name">
      <a class="navbar-brand" href="{{ url_for('home.homepage') }}">#<span>CAUCA</span>AGRO<span>SOSTENIBLE</span></a>
    </h1>

    <div class="collapse navbar-collapse" id="navbarNav">

      <ul class="navbar-nav mr-auto mt-2">
        <li class="nav-item active"></li>
      </ul>

      <ul class="navbar-nav ml-auto mr-auto mt-2 mt-lg-0">
        {% if current_user.is_authenticated %}
        {% if current_user.is_admin %}
        <li class="nav-item ml-3">
          <a class="nav-link active" href="{{ url_for('home.admin_dashboard') }}">Dashboard</a>
        </li>

        <li class="nav-item ml-3">
          <a class="nav-link" href="{{ url_for('admin.list_products') }}">Productos</a>
        </li>

        <li class="nav-item ml-3">
          <a class="nav-link" href="{{ url_for('admin.list_organizaciones') }}">Organizaciones</a>
        </li>

        <li class="nav-item ml-3">
          <a class="nav-link" href="{{ url_for('admin.list_inversionistas') }}">Inversionistas</a>
        </li>
        
        <li class="nav-item ml-3">
          <a class="nav-link" href="{{ url_for('admin.list_eventos') }}">Eventos</a>
        </li>

        <li class="nav-item ml-3">
          <a class="nav-link" href="{{ url_for('admin.list_orders') }}">Orders</a>
        </li>

        <li class="nav-item ml-3">
          <a class="nav-link" href="{{ url_for('users.cart') }}">Cart<span class="badge badge-light">{{ count
              }}</span></a>
        </li>

        {% else %}
        <li class="nav-item ml-3">
          <a class="nav-link" href="{{ url_for('users.cart') }}">Cart<span class="badge badge-light">{{ count
              }}</span></a>
        </li>
        {% endif %}
        <li class="nav-item dropdown ml-3">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true"
            aria-expanded="false">
            Hi, {{ current_user.firstname }}!
          </a>

          <div class="dropdown-menu">
            <a class="dropdown-item" href="{{ url_for('users.profile') }}">Profile</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{{ url_for('auth.logout') }}">Logout</a>
          </div>
        </li>

        {% else %}
        <li class="nav-item active ml-3">
          <a class="nav-link" href="{{ url_for('home.homepage') }}">Home <span class="sr-only">(current)</span></a>
        </li>

        <li class="nav-item ml-3">
          <a class="nav-link" href="{{ url_for('users.cart') }}">Cart<span class="badge badge-light">{{ count
              }}</span></a>
        </li>

        <li class="nav-item ml-3">
          <a class="nav-link" href="{{ url_for('auth.register') }}">Register</a>
        </li>

        <li class="nav-item ml-3">
          <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>
</div>

{% endblock %}

app/templates/promotions.html
{% block promo %}
  <!-- banner -->
<div class="banner">
  <div class="xf">
    <div class="bd-example" >
    <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
      <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
      <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
      </ol>
    <div class="carousel-inner">
    <div class="carousel-item active" style="max-width:100%;">
      <img src="{{url_for('static', filename='Oferta.png')}}" class="d-block carousel-img-height" alt="...">
    <div class="carousel-caption d-none d-md-block">
      <p>
        <a href="{{url_for('home.homepage')}}"> 
        Ofertas Especiales</a> 
      </p>
    </div>
  </div>
                                            
{% for i in products %}
{% if i.id in sorter %}
  <div class="carousel-item" style="max-width:100%;">
    <a href="{{url_for('home.product_details',product_name = i.product_name)}}">
    <img src="{{i.product_image}}" class="d-block  carousel-img-height" alt="...">
    <div class="carousel-caption d-none d-md-block">
      <h5>Producto en descuento</h5>
      <p>{{i.product_name}}</p>
    </div>
    </a>
  </div>
{%endif%}
{%endfor %}
                                            
    <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>

    <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>
</div>  
</div>  

{% endblock %}